"""Generate the file-compatible browser dataset from the shared JSON source."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
data = json.loads((root / "data.json").read_text(encoding="utf-8"))
(root / "assets/data.js").write_text(
    "// Generated by scripts/build_data.py. Edit data.json.\nglobalThis.DestaData = "
    + json.dumps(data, ensure_ascii=False, indent=2) + ";\n", encoding="utf-8"
)
